name: Rust

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check Inno Setup version
      run: iscc.exe --version
    - name: Download Binary Dependencies
      run: python script/download_deps.py
    - name: Switch to nightly
      run: rustup default nightly
    - name: Install daisyUI
      run: npm i -D daisyui@latest
    - name: Build release
      run: cargo build --release
    - name: Build CSS
      run: npx tailwindcss -i ./webui_template/index.css -o ./webui/index.css
    - name: Build Installer
      run: \"C:\Program Files (x86)\Inno Setup 6\ISCC.exe\" installer\windows\main.iss
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          target/innosetup/youtube-dl-server-setup.exe
